<?php

require_once dirname(__FILE__) . '/../../../php/classes/class_MemberGroupSteel.php';

/**
 * Test class for MemberGroupSteel.
 * Generated by PHPUnit on 2011-08-31 at 05:22:44.
 */
class MemberGroupSteelTest extends PHPUnit_Framework_TestCase {

    /**
     * @var MemberGroupSteel
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new MemberGroupSteel;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {

    }

    public function testGet_1() {
        $this->object->get('"C245" 240.262      0.    0.95    400.'."\r\n".'1     1.     0.'."\r\n".'0     0.     0.     0.     0.     0.     0.     0.      0      0'."\r\n".'Name="+4.000 - B3_1" : 54 55 99 102 103 106 107 110');

        $this->assertEquals('C245', $this->object->steel_type);
        $this->assertEquals(240.262, $this->object->steel_Ry);
        $this->assertEquals(0.95, $this->object->gamma_c);
        $this->assertEquals(400, $this->object->flexibility);
        $this->assertEquals(TRUE, $this->object->group_type);
        $this->assertEquals(1, $this->object->mu_XZ);
        $this->assertEquals(0, $this->object->mu_XY);
        $this->assertEquals('+4.000 - B3_1', $this->object->name);
        $this->assertEquals(array(54,55,99,102,103,106,107,110), $this->object->list);
    }

    public function testGet_2() {
        $this->object->get('"C245" 240.262      0.      1.    120.'."\r\n".' 0     2.     1.'."\r\n".' 0     0.     0.     0.     0.     0.     0.     0.      0      0'."\r\n".' Name="Column 1_9" : 60 123 124');

        $this->assertEquals('C245', $this->object->steel_type);
        $this->assertEquals(240.262, $this->object->steel_Ry);
        $this->assertEquals(1, $this->object->gamma_c);
        $this->assertEquals(120, $this->object->flexibility);
        $this->assertEquals(FALSE, $this->object->group_type);
        $this->assertEquals(2, $this->object->mu_XZ);
        $this->assertEquals(1, $this->object->mu_XY);
        $this->assertEquals('Column 1_9', $this->object->name);
        $this->assertEquals(array(60,123,124), $this->object->list);
    }

    public function testSet_1() {
        $this->object->steel_type = 'C245';
        $this->object->steel_Ry = 240.262;
        $this->object->gamma_c = 0.95;
        $this->object->flexibility = 400;
        $this->object->group_type = 1;
        $this->object->mu_XZ = 1;
        $this->object->mu_XY = 0;
        $this->object->name = '+4.000 - B3_1';
        $this->object->list = array(54,55,99,102,103,106,107,110);

        $this->assertEquals('"C245" 240.262 0 0.95 400'."\r\n".'1 1.00 0.00'."\r\n".'0     0.     0.     0.     0.     0.     0.     0.      0      0'."\r\n".'Name="+4.000 - B3_1" : 54 55 99 102 103 106 107 110',  $this->object->set());
    }

    public function testSet_2() {
        $this->object->steel_type = 'C245';
        $this->object->steel_Ry = 240.262;
        $this->object->gamma_c = 1;
        $this->object->flexibility = 120;
        $this->object->group_type = 0;
        $this->object->mu_XZ = 2;
        $this->object->mu_XY = 1;
        $this->object->name = 'Column 1_9';
        $this->object->list = array(60,123,124);

        $this->assertEquals('"C245" 240.262 0 1.00 120'."\r\n".'0 2.00 1.00'."\r\n".'0     0.     0.     0.     0.     0.     0.     0.      0      0'."\r\n".'Name="Column 1_9" : 60 123 124',  $this->object->set());
    }

}

?>
