<?php

require_once dirname(__FILE__) . '/../../../php/classes/class_MemberList.php';

/**
 * Test class for MemberList.
 * Generated by PHPUnit on 2011-08-28 at 13:51:07.
 */
class MemberListTest extends PHPUnit_Framework_TestCase {

    /**
     * @var MemberList
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new MemberList;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {

    }

    /**
     * Generated from @assert ('1') ==  array (1).
     */
    
    public function testGet_member_list() {
        $this->assertEquals(
                array(1),
                $this->object->get_member_list('1')
        );
    }

    /**
     * Generated from @assert ('129 r 133 2') ==  array (129,131,133).
     */
    public function testGet_member_list2() {
        $this->assertEquals(
                array(129, 131, 133),
                $this->object->get_member_list('129 r 133 2')
        );
    }

    /**
     * Generated from @assert ('2 501-503 505') ==  array (2,501,502,503,505).
     */
    public function testGet_member_list3() {
        $this->assertEquals(
                array(2, 501, 502, 503, 505),
                $this->object->get_member_list('2 501-503 505')
        );
    }

    /**
     * Generated from @assert (' 129 r 138 3 140   142 155-157 ') ==  array (129,132,135,138,140,142,155,156,157).
     */
    public function testGet_member_list4() {
        $this->assertEquals(
                array(129, 132, 135, 138, 140, 142, 155, 156, 157),
                $this->object->get_member_list(' 129 r 138 3 140   142 155-157 ')
        );
    }

    /**
     * Generated from @assert (array(1)) ==  '1'.
     */
    public function testSet_member_list() {
        $this->assertEquals(
                '1',
                $this->object->set_member_list(array(1))
        );
    }

    /**
     * Generated from @assert (array(1,2,3)) ==  '1-3'.
     */
    public function testSet_member_list2() {
        $this->assertEquals(
                '1-3',
                $this->object->set_member_list(array(1, 2, 3))
        );
    }

    /**
     * Generated from @assert (array(1,3,5,7,10)) ==  '1 r 7 2 10'.
     */
    public function testSet_member_list3() {
        $this->assertEquals(
                '1 r 7 2 10',
                $this->object->set_member_list(array(1, 3, 5, 7, 10))
        );
    }

    /**
     * Generated from @assert (array(1,2,3,5,7,9,10,11,12,13)) ==  '1-3 5 r 9 2 10-13'.
     */
    public function testSet_member_list4() {
        $this->assertEquals(
                '1-3 5 r 9 2 10-13',
                $this->object->set_member_list(array(1, 2, 3, 5, 7, 9, 10, 11, 12, 13))
        );
    }

    /**
     * Generated from @assert (array(1,2,3,6,8,10,13,14,15,16)) ==  '1-3 6 r 10 2 13-16'.
     */
    public function testSet_member_list5() {
        $this->assertEquals(
                '1-3 6 r 10 2 13-16',
                $this->object->set_member_list(array(1, 2, 3, 6, 8, 10, 13, 14, 15, 16))
        );
    }

    /**
     * Generated from @assert (array(1,65,72)) ==  '1 65 72'.
     */
    public function testSet_member_list6() {
        $this->object->list = array(1, 65, 72);
        $this->assertEquals(
                '1 65 72',
                $this->object->set_member_list()
        );
    }

    public function testSet_member_list7() {
        $this->object->list = array(314);
        $this->assertEquals(
                '314',
                $this->object->set_member_list()
        );
    }

}

?>
