<?php

require_once dirname(__FILE__) . '/../../../php/classes/class_Member.php';

/**
 * Test class for Member.
 * Generated by PHPUnit on 2011-09-10 at 11:07:38.
 */
class MemberTest extends PHPUnit_Framework_TestCase {

    /**
     * @var Member
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Member;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {

    }

    /**
     * Generated from @assert ('36 0 5 6 7 8 9 10 11 12') ==  array (36,0,array(5, 6, 7, 8, 9, 10, 11, 12)).
     */
    public function testGet() {
        $this->assertEquals(
                array(36, 0, array(5, 6, 7, 8, 9, 10, 11, 12)),
                $this->object->get('36 0 5 6 7 8 9 10 11 12')
        );
    }

    /**
     * Generated from @assert ('44 0 1 2 3 4') ==  array (44,0,array(1, 2, 3, 4)).
     */
    public function testGet2() {
        $this->assertEquals(
                array(44, 0, array(1, 2, 3, 4)),
                $this->object->get('44 0 1 2 3 4')
        );
    }

    /**
     * Generated from @assert ('55 10 5 6') ==  array (55,10,array(5, 6)).
     */
    public function testGet3() {
        $this->assertEquals(
                array(55, 10, array(5, 6)),
                $this->object->get('55 10 5 6')
        );
    }

    public function testSet() {
       $this->object->type = 3;
       $this->object->section = 0;
        $this->object->list = array(1,2,3,4);

        $this->assertEquals(
                '3 0 1 2 3 4',
                $this->object->set()
        );
    }

}

?>
