<?php

require_once dirname(__FILE__) . '/../../../php/classes/class_Node.php';

/**
 * Test class for Node.
 * Generated by PHPUnit on 2011-09-10 at 07:52:23.
 */
class NodeTest extends PHPUnit_Framework_TestCase {

    /**
     * @var Node
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Node;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {

    }

    /**
     * Generated from @assert (' 56.33') ==  array (56.33,0,0).
     */
    public function testGet() {
        $this->assertEquals(
                array(56.33, 0, 0),
                $this->object->get(' 56.33')
        );
    }

    /**
     * Generated from @assert ('73.44 0.3 ') ==  array (73.44,0.3,0).
     */
    public function testGet2() {
        $this->assertEquals(
                array(73.44, 0.3, 0),
                $this->object->get('73.44 0.3 ')
        );
    }

    /**
     * Generated from @assert ('23.44 54.2 3') ==  array (23.44,54.2,3).
     */
    public function testGet3() {
        $this->assertEquals(
                array(23.44, 54.2, 3),
                $this->object->get('23.44 54.2 3')
        );
    }

    /**
     * Generated from @assert ('37.5 0 0.3') ==  array (37.5,0,0.3).
     */
    public function testGet4() {
        $this->assertEquals(
                array(37.5, 0, 0.3),
                $this->object->get('37.5 0 0.3')
        );
    }

    public function testSet1() {
        $this->object->x = 37.5;
        $this->object->y = 45.33;
        $this->object->z = 0.26;
        
        $this->assertEquals(
                '37.5 45.33 0.26',
                $this->object->set()
        );
    }

}

?>
