<?php
namespace php\classes\ScadFile;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-01-13 at 18:21:42.
 */
class ScadFileTest extends \PHPUnit_Framework_TestCase
{
    const TEST_FILENAME = "scad21TestFile_01.SPR";
    const CORRECT_DOCS_DESCRIPTION_ADDRESS = 103129;
    
    protected $object;

    protected function setUp()
    {
        $testFileContent = file_get_contents(realpath(__DIR__ . DIRECTORY_SEPARATOR . self::TEST_FILENAME));
        $this->object = new ScadFile($testFileContent);
    }

    public function testIsObjectCreated() {
        $isObjectCreated = !is_null($this->object);
        $this->assertTrue($isObjectCreated);
    }
    
    public function testGetCorrectFileFooterAddress() {
        $this->assertEquals(self::CORRECT_DOCS_DESCRIPTION_ADDRESS,
                $this->object->getFileFooterAddress());
    }

}
